### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by jonathan-dilorenzo** [janestreet/async_extra#10]
Both Tcp.with_connection and Tcp.connect state that they are used with:
> [command] ~host ~port f

However, they no longer take labeled arguments host or port, and the new equivalent seems to be:
> [command] (Core.Host_and_port.create ~host ~port |> Tcp.Where_to_connect.of_host_and_port) f

**Comment by bcc32** [comment]
This was fixed by #12.
