### ISSUE TITLE
Where is Udp?

### ISSUE THREAD

**Issue by copy** [janestreet/async_extra#13]
I can't seem to find the v0.12 version of the `Udp` module anywhere. The [announcement](https://discuss.ocaml.org/t/ann-v0-12-release-of-jane-street-packages/3499) mentions an `Async_udp` library, but it doesn't seem to be in any of Jane Stree's repositories either.

**Comment by trefis** [comment]
Indeed. Apparently the split that happened internally got reflected as a removal externally.
We'll fix that, and might also do a minor release of v0.12.

**Comment by Leonidas-from-XIV** [comment]
I [ran across the same today](https://discuss.ocaml.org/t/ann-v0-12-release-of-jane-street-packages/3499/4). @trefis, is there any update on this? So far this is what is keeping us on v0.11. I saw some packages already got a `v0.12.1` refresh.

**Comment by trefis** [comment]
Sorry for the delay.
There will be a minor release "soon" to add 4.08 support to our packages that miss it. We will release async_extra (with async_udp) at that time.

**Comment by xclerc** [comment]
We are about to release a new version of `async_extra`,
we only need a new release of `ppxlib` (review being in
progress).

**Comment by mbacarella** [comment]
I guess this didn't happen?  Is v0.12 just going to be missing Async Udp?

As a workaround I just copy/pasted async_udp.ml (and import.ml) from async_extra.v0.11 into my project in the meantime so no rush I guess.  It's _probably_ not violating Jane Street's IP or anything. :roll_eyes:

**Comment by Leonidas-from-XIV** [comment]
@mbacarella Maybe you could make this into an OPAM package? That way it would make `v0.12` usable for people that need UDP?

**Comment by mbacarella** [comment]
@Leonidas-from-XIV that's not nearly as illegal, but okay.

See README at https://github.com/mbacarella/async_udp

Basically has instructions on how to opam pin the repo.

Let me know how it goes.

**Comment by copy** [comment]
Closing this since Async_udp has been released as a stand-alone project: https://github.com/ocaml/opam-repository/pull/15114
