### ISSUE TITLE
Extra argument to Typed_tcp.Make

### ISSUE THREAD

**Issue by arjunguha** [janestreet/async_extra#3]
This is a question, not an issue.

In version 112.17, Typed_tcp.Make takes an extra argument:

https://github.com/janestreet/async_extra/blob/master/lib/typed_tcp.mli#L13

It is easy to adapt my code to this new interface, but I'm curious why this is the case. I couldn't figure it out from the release notes.

**Comment by diml** [comment]
Indeed, there is only a note about it in the [CHANGES.md of core_kernel](https://github.com/janestreet/core_kernel/blob/master/CHANGES.md). The change concerns a few JS libraries.

**Comment by arjunguha** [comment]
Got it. Didn't realize this applied to Typed_tcp as well. thanks.
