### ISSUE TITLE
Use errno.h

### ISSUE THREAD

**Issue by madroach** [janestreet/async_extra#4]
Hi,

building async_extra fails on OpenBSD because errno is not defined in `<sys/errno.h>`. According to the Linux and *BSD manpages simply `<errno.h>` should be included.

Christopher

http://man7.org/linux/man-pages/man3/errno.3.html
http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man2/errno.2

```
--- src/rpc_transport_low_latency_stubs.c
+++ src/rpc_transport_low_latency_stubs.c
@@ -1,6 +1,6 @@
 #include <stdlib.h>
+#include <errno.h>
 #include <sys/uio.h>
-#include <sys/errno.h>

 #include <caml/mlvalues.h>
 #include <caml/bigarray.h>
```

**Comment by diml** [comment]
Thanks, will be part of the next release

**Comment by rneswold** [comment]
Fails on NetBSD for the same reason. Looking forward to the update.

**Comment by seliopou** [comment]
This change is present in the current release. Closing.
